### ISSUE TITLE
accuracy stuck at around 30%

### ISSUE THREAD

**Issue by jeff-regier** [aakhundov/tf-attend-infer-repeat#2]
Thanks for making this code available! I ran it overnight but accuracy seems stuck at around 30%. Is that to be expected? Do I need to change some settings? 

```
iteration 932821	loss 170.042	accuracy 0.39
iteration 932822	loss 162.404	accuracy 0.31
iteration 932823	loss 138.939	accuracy 0.38
iteration 932824	loss 206.878	accuracy 0.25
iteration 932825	loss 152.315	accuracy 0.34
iteration 932826	loss 216.359	accuracy 0.23
iteration 932827	loss 176.608	accuracy 0.30
iteration 932828	loss 208.651	accuracy 0.27
iteration 932829	loss 183.779	accuracy 0.25
iteration 932830	loss 177.368	accuracy 0.28
iteration 932831	loss 173.904	accuracy 0.30
iteration 932832	loss 181.539	accuracy 0.31
iteration 932833	loss 155.489	accuracy 0.34
iteration 932834	loss 162.920	accuracy 0.33
iteration 932835	loss 172.731	accuracy 0.31
iteration 932836	loss 250.412	accuracy 0.28
```

**Comment by aprams** [comment]
Hi jeff,

This is a problem we are well aware of and looking for a solution. Getting to 95-100% accuracy only happens in about 1-2 out of 10 runs. 
This is probably due to the fact, that the model first learns to attend all the time when possible except for empty images. Therefore it often learns to attend the 2nd digit with the 3rd attention window or similar cases. We've been looking a lot into this, but didn't find a good way to fix that. If you're still stuck at 30% accuracy after 50k iterations, that run probably won't work. In general the model won't learn much after 100k iterations. 
We are very open to hints or suggestions on how to tackle that problem.
Thank you for your insights!

**Comment by aakhundov** [comment]
Hi Jeff,

We've made some modifications of the original AIR model. Most notably, continuous relaxation of originally discrete z<sub>pres</sub>. The details of this and some other clarifications are in the updated README.md.

As a result of this change, stability of the training has become substantially better (actually, it is now close to 100%). Would you please get the latest version and run training.py (after generating the dataset with multi_mnist.py, of course) and confirm that it converges? We've also added live demo (demo.py) and embeddings generator (embeddings.py), which might be interesting.

Thank you!
